- hosts: localhost
  become: true
  pre_tasks: 
    - name: Update Cache
      apt: 
        update_cache: true
      tags: 
      - node
      - zsh
  tasks:  
  - name: Install zsh
    apt: name=zsh
  - name: Add zsh to /etc/shells
    shell: command -v zsh | sudo tee -a /etc/shells
  - name: Change Shell
    shell: sudo chsh -s "$(command -v zsh)" "${USER}"
  - name: Install OhMyZsh!
    shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  - name: Install the Zsh Plugin for AutoSuggestions
    ansible.builtin.git:
      repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
      dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  - name: Install the Zsh Syntax Highlighting
    ansible.builtin.git:
      repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
      dest: "~/.oh-my-zsh/plugins/zsh-syntaxhighlighting"
  - name: update our zshrc
    shell: sed -i 's/(git/(git zsh-autosuggestions zsh-syntaxhighlighting' ~/.zshrc
  - name: install node
    apt:
      name: ['node.js', 'npm']
    tags: 
    - node
  - name: Install n
    npm: name=n
    tags: 
    - node
  - name: n 14
    shell: n 14
    tags: 
    - node
  
    