- hosts: localhost
  become: true
  tasks:  
  - include_tasks: ../common/git-setup.yml
  - include_tasks: ../common/zsh-setup.yml
  - include_tasks: tasks/fonts-setup.yml
  - include_tasks: tasks/java-setup.yml
  - include_tasks: tasks/node-setup.yml
  - include_tasks: tasks/apps-setup.yml
    