- hosts: localhost
  become: true
  pre_tasks: 
    - name: Update Cache
      apt: 
        force_apt_get: true
        update_cache: true
      tags: 
      - setup
      - core
  tasks:  
  - include_tasks: ../common/git-setup.yml
  - include_tasks: ../common/zsh-setup.yml
  - include_tasks: tasks/core-setup.yml
  - include_tasks: tasks/node-setup.yml
  - include_tasks: tasks/apps-setup.yml
  - include_tasks: tasks/fonts-setup.yml
  - include_tasks: ../common/npm-packages.yml
    